# ETAPA 1: Construcción (Build)
# Usamos Node para instalar las librerías y compilar el código de React
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# ETAPA 2: Servidor de Producción (Nginx)
# Una vez compilado, solo necesitamos un servidor web ligero para entregar los archivos
FROM nginx:stable-alpine
# Copiamos la carpeta 'dist' (donde Vite guarda la web compilada) al servidor Nginx
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]