version: "3.8"

services:

  db:
    image: postgres:15-alpine
    container_name: base_datos
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
      - ./images:/app/images:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: ./server
    container_name: api_server
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/app
      - ./images:/app/images:ro

  frontend:
    build: ./frontend
    container_name: tienda_frontend
    ports:
      - "3000:80" # Entraréis por http://localhost:3000
    depends_on:
      - server

volumes:
  postgres_data: