# 3 servicios
    # Base datos
    # Servidor fast_api
    # Frontend

#Definimos la base de datos, asegurarse de haber cargado las var de entorno del .env
#Creamos un volumen para la bbdd, otro para las imagenes y otro para los scripts de inicializacion
services:
  db:
    image: postgres:15-alpine
    container_name: base_datos
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
      - ./images:/app/images:ro

volumes:
  postgres_data:

